PREFIX=i586-pc-msdosdjgpp
CC=$(PREFIX)-gcc

CFLAGS = -g -Wall -pedantic -Ofast -march=i386 -mtune=i586
LDFLAGS =

TARGETS=8080TEST.EXE SEG20.EXE
src = $(wildcard *.c)
obj = $(src:.c=.o)

.PHONY: all clean install

all: $(bin)

8080TEST.EXE: i8080_tests.c
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)
	@$(PREFIX)-size $@
	@du -b $@

SEG20.EXE: seg20.c
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)
	@$(PREFIX)-size $@
	@du -b $@

clean:
	-rm $(TARGETS) $(obj)

install: $(TARGETS)
	cp -p $^ ~/Emulation/DOS/C/code/8080/
